# Generated by Django 6.0.3 on 2026-08-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='รูปสินค้า'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='ใช้เมื่อไม่ได้อัปโหลดไฟล์ ถ้าอัปโหลดไฟล์ไว้ระบบจะใช้ไฟล์ก่อน', verbose_name='ลิงก์รูปสินค้า'),
        ),
    ]
