# Generated by Django 6.0.3 on 2026-04-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อผลไม้')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('stock', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fruits/', verbose_name='รูปภาพ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
            ],
        ),
    ]
