# Generated by Django 6.0.3 on 2026-04-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='ทะเบียนรถ')),
                ('vehicle_type', models.CharField(choices=[('car', 'รถยนต์'), ('motorcycle', 'มอเตอร์ไซค์'), ('truck', 'รถบรรทุก')], max_length=50, verbose_name='ประเภทรถ')),
                ('entry_time', models.DateTimeField(verbose_name='เวลาเข้า')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลาออก')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้ขับ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
            ],
        ),
    ]
